# Generated by Django 5.2.17 on 2026-10-08 05:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwsCostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload', models.JSONField(help_text='Aggregated payload containing daily, by_service, forecast, summary, resources, and health telemetry.')),
                ('source', models.CharField(default='scheduled', help_text='Origin of snapshot (e.g. scheduled, management_command, manual, bootstrap)', max_length=50)),
                ('status', models.CharField(default='success', help_text='Status of snapshot: success or error', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AWS Cost Snapshot',
                'verbose_name_plural': 'AWS Cost Snapshots',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
