# Generated by Django 5.2.17 on 2026-08-19 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('expected_interval_minutes', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'hospitals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patient_uhid', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('initial_registration_date', models.DateTimeField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('encounter_no', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_date', models.DateTimeField(blank=True, null=True)),
                ('visit_type', models.CharField(blank=True, max_length=50, null=True)),
                ('area_code', models.CharField(blank=True, max_length=50, null=True)),
                ('area_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bed', models.CharField(blank=True, max_length=50, null=True)),
                ('clinician_code', models.CharField(blank=True, max_length=50, null=True)),
                ('clinician_name', models.CharField(blank=True, max_length=255, null=True)),
                ('specialty_code', models.CharField(blank=True, max_length=50, null=True)),
                ('specialty_name', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hospital', models.ForeignKey(blank=True, db_column='hospital_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'encounters',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patient_uhid', models.CharField(blank=True, max_length=100, null=True)),
                ('encounter_no', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_type', models.CharField(blank=True, max_length=50, null=True)),
                ('discharged_by_user_code', models.CharField(blank=True, max_length=50, null=True)),
                ('discharged_by_user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hospital', models.ForeignKey(blank=True, db_column='hospital_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discharges', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'discharges',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DataIngestionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(blank=True, max_length=50, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('expected_at', models.DateTimeField(blank=True, null=True)),
                ('record_count', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('data_size_mb', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hospital', models.ForeignKey(blank=True, db_column='hospital_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_logs', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'data_ingestion_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(blank=True, max_length=50, null=True)),
                ('severity', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('CRITICAL', 'CRITICAL')], default='WARNING', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('metric_name', models.CharField(blank=True, max_length=50, null=True)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ACKNOWLEDGED', 'ACKNOWLEDGED'), ('RESOLVED', 'RESOLVED')], default='ACTIVE', max_length=20)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hospital', models.ForeignKey(blank=True, db_column='hospital_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'alerts',
                'managed': True,
            },
        ),
    ]
