# Generated by Django 5.2.17 on 2026-08-18 11:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='HospitalID must be in the format HOSP000001 (HOSP + 6-digit sequence)', regex='^HOSP\\d{6}$')])),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('delayed', 'Delayed'), ('warning', 'Warning'), ('critical', 'Critical'), ('offline', 'Offline')], default='healthy', max_length=50)),
                ('last_data_received', models.CharField(default='Just now', max_length=100)),
                ('expected_data_time', models.CharField(default='12:00 PM', max_length=100)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('data_frequency', models.IntegerField(default=30)),
                ('data_volume_mb', models.FloatField(default=0.0)),
                ('records_received', models.IntegerField(default=0)),
                ('service_status', models.CharField(choices=[('running', 'Running'), ('degraded', 'Degraded'), ('stopped', 'Stopped')], default='running', max_length=50)),
                ('data_quality', models.IntegerField(default=100)),
                ('aws_cost', models.IntegerField(default=0)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(default='ap-south-1', max_length=50)),
                ('api_endpoint', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'hospitals',
                'constraints': [models.UniqueConstraint(fields=('hospital_id',), name='uq_hospital_id'), models.CheckConstraint(condition=models.Q(('hospital_id__regex', '^HOSP\\d{6}$')), name='chk_hospital_id_format')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('last_received', models.CharField(default='', max_length=100)),
                ('expected_time', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='delay', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
    ]
